set_property IOSTANDARD LVCMOS33 [get_ports {pos[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pos[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sync_rst]
set_property PACKAGE_PIN N15 [get_ports a]
set_property PACKAGE_PIN R18 [get_ports b]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property PACKAGE_PIN P16 [get_ports rst]
set_property PACKAGE_PIN T18 [get_ports sync_rst]
set_property PACKAGE_PIN U14 [get_ports {pos[7]}]
set_property PACKAGE_PIN U19 [get_ports {pos[6]}]
set_property PACKAGE_PIN W22 [get_ports {pos[5]}]
set_property PACKAGE_PIN V22 [get_ports {pos[4]}]
set_property PACKAGE_PIN U21 [get_ports {pos[3]}]
set_property PACKAGE_PIN U22 [get_ports {pos[2]}]
set_property PACKAGE_PIN T21 [get_ports {pos[1]}]
set_property PACKAGE_PIN T22 [get_ports {pos[0]}]

create_clock -period 10.000 -name MCLK -waveform {0.000 5.000} [get_ports clk]

