# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.cache/wt [current_project]
set_property parent.project_path M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/lab4processor.bd
set_property used_in_implementation false [get_files -all m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/ip/lab4processor_processing_system7_0_0/lab4processor_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/ip/lab4processor_processing_system7_0_0/lab4processor_processing_system7_0_0.dcp]
set_property used_in_implementation false [get_files -all m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/ip/lab4processor_proc_sys_reset_0_0/lab4processor_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/ip/lab4processor_proc_sys_reset_0_0/lab4processor_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/ip/lab4processor_proc_sys_reset_0_0/lab4processor_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/ip/lab4processor_proc_sys_reset_0_0/lab4processor_proc_sys_reset_0_0.dcp]
set_property used_in_implementation false [get_files -all m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/ip/lab4processor_auto_pc_0/lab4processor_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/ip/lab4processor_auto_pc_0/lab4processor_auto_pc_0.dcp]
set_property used_in_implementation false [get_files -all M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/lab4processor_ooc.xdc]
set_property is_locked true [get_files M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/lab4processor.bd]

read_vhdl -library xil_defaultlib {
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/p_ctrl_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/clkdiv_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/pos_meas_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/rstsynch_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/p_ctrl_rtl.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/subprog_pck.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/seg7_ctrl_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/pos_ctrl_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/lab4_pck.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/rstsynch_rtl.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/pos_meas_rtl.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/clkdiv_rtl.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/cru_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/pos_seg7_ctrl_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/lab4reg_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/seg7_ctrl_rtl.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/pos_ctrl_str.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/axi4pifb_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/cru_str.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/lab4reg_rtl.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/ram_lab4_rtl.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/lab4_top_ent.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/pos_seg7_ctrl_str.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/axi4pifb_rtl.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/INF3430_Lab4/INF3430_Lab4.srcs/sources_1/bd/lab4processor/hdl/lab4processor_wrapper.vhd
  M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/sources_1/imports/sim/lab4_top_str.vhd
}
read_xdc M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/constrs_1/imports/constraints/constraints_lab4.xdc
set_property used_in_implementation false [get_files M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/RAM_RTL_TEST_INF3430_Lab4/RAM_RTL_TEST_INF3430_Lab4.srcs/constrs_1/imports/constraints/constraints_lab4.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top lab4_top -part xc7z020clg484-1
write_checkpoint -noxdef lab4_top.dcp
catch { report_utilization -file lab4_top_utilization_synth.rpt -pb lab4_top_utilization_synth.pb }
