# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/ram_lab4/ram_lab4.xci
# IP: The module: 'ram_lab4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/ram_lab4/ram_lab4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_lab4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: M:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/ram_lab4/ram_lab4.xci
# IP: The module: 'ram_lab4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: m:/pc/Desktop/INF3430/INF3430-Lab-4/Vivado/ram_lab4/ram_lab4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_lab4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
